### ISSUE TITLE
自定义命令和发布第三方平台报错

### ISSUE THREAD

**Issue by krapnikkk** [Hunterib/Laya-polea#2]
是否有支持【自定义命令】和【发布第三方平台】的计划？

**Comment by Hunterib** [comment]
关于【自定义命令】 目前提供的方式只有编译、发布命令的那种config.name.ts 的方式，可以定制自己的插件具体的参考 plugin 目录下的两个插件
关于【发布第三方平台】可以加入计划中

**Comment by Hunterib** [comment]
关于发布第三方发布平台，不知到您有什么好的建议呢，我这边还在考虑中
